# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #config.vm.box = "hashicorp-education/ubuntu-24-04"
  config.vm.box = "bento/ubuntu-24.04"
  #config.vm.box = "ubuntu/jammy64"
  #config.vm.box_version = "202508.03.0"
  config.vm.network "public_network", bridge: true
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end
  config.vm.provision "shell", inline: <<-SHELL
    #set -e
    apt update
    apt install -y build-essential pkg-config \
                   python3 python3-pip python3-venv python-is-python3 \
                   curl openssl cmake git autoconf libtool libgflags-dev libgtest-dev clang libc++-dev \
                   libgrpc++-dev protobuf-compiler-grpc protobuf-compiler libabsl-dev libpqxx-dev libprotobuf-dev

    #download latest version of abseil, compile and install
    cd /tmp && git clone https://github.com/abseil/abseil-cpp.git
    cd /tmp/abseil-cpp && git tag | grep -E "2023|2024" | tail -5   
    cd /tmp/abseil-cpp && git checkout 20240722.0
    cd /tmp/abseil-cpp && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_BUILD_TYPE=Release -DABSL_BUILD_TESTING=OFF -DABSL_USE_EXTERNAL_GOOGLETEST=ON ..
    cd /tmp/abseil-cpp/build && make install

    # Install gRPC and Protocol Buffers from source
    #export MY_INSTALL_DIR=$HOME/.local
    # mkdir -p $MY_INSTALL_DIR
    # # Install gRPC and Protocol Buffers from source
    # cd /tmp
    # git clone --recurse-submodules -b v1.74.0 --depth 1 --shallow-submodules https://github.com/grpc/grpc
    # cd grpc
    # mkdir -p cmake/build
    # pushd cmake/build
    # cmake -DgRPC_INSTALL=ON \
    #       -DgRPC_BUILD_TESTS=OFF \
    #       -DCMAKE_CXX_STANDARD=17 \
    #       -DCMAKE_INSTALL_PREFIX=$MY_INSTALL_DIR \
    #       ../..
    # make -j 4
    # make install
    # popd
    
  SHELL
end
